// Add invited guests here. The key is used in links like index.html?guest=gideon-kalanzi.
window.INVITE_GUESTS = {
  "mrs.-nsereko-rose": "Mrs. Nsereko Rose",
  "mr.-and-mrs.-nsambu": "Mr. & Mrs. Nsambu",
  "ms.-linda-nambalirwa": "Ms. Linda Nambalirwa",
  "mrs.-lillian-sonko": "Mrs. Lillian Sonko",
  "mr.-and-mrs.-sekajja-arthur": "Mr. & Mrs. Sekajja Arthur",
  "mrs.-ruth-mirembe": "Mrs.Ruth Mirembe",
  "aunt-namala-berna": "Aunt Namala Berna",
  "mr.-and-mrs.-kawooya-wilberforce": "Mr. & Mrs. Kawooya Wilberforce",
  "mr.-and-mrs.-gayi-eric-kasule": "Mr. & Mrs. Gayi Eric Kasule",
  "kasujja-james-raymond": "Kasujja James Raymond",
  "simon-peter": "Simon Peter",
  "mr.-and-mrs.-mulindwa-john": "Mr. & Mrs. Mulindwa John",
  "mr.-and-mrs.-jean-clement-sekiranda": "Mr. & Mrs. Jean Clement Sekiranda",
  "ms.-cissy-nansamba": "Ms. Cissy Nansamba",
  "gideon-kalanzi": "Gideon Kalanzi",
  "ms.-deborah-arinaitwe": "Ms. Deborah Arinaitwe",
  "ms.-judith-atholere": "Ms. Judith Atholere",
  "ms.-gloria-lamunu": "Ms. Gloria Lamunu",
  "ms.-etot-james-lucas": "Ms. Etot James Lucas",
  "mr.-karugaba-joseph": "Mr. Karugaba Joseph",
  "ms.-babirye-stella": "Ms. Babirye Stella",
  "ms.-lamunu-gloria": "Ms. Lamunu Gloria",
  "mr.-ssensozi-james": "Mr. Ssensozi James",
  "aunt-annet-nabuuma": "Aunt Annet Nabuuma",
  "mr.-noah": "Mr. Noah",
  "aunt-cathy-wanyana": "Aunt Cathy Wanyana",
  "mr.-and-mrs.-sserubiri": "Mr. & Mrs. Sserubiri",
  "pastor-mukisa": "Pastor Mukisa",
  "mr.-and-mrs.-ssemanda": "Mr. & Mrs. Ssemanda",
  "mr.-and-mrs.-bwogi-tom": "Mr. & Mrs. Bwogi Tom",
  "mr.-lukwata-andrew": "Mr. Lukwata Andrew",
  "ms.-dorcus": "Ms. Dorcus",
  "mr.-and-mrs.-mutebi": "Mr. & Mrs. Mutebi",
  "mr.-kirabo-eric": "Mr. Kirabo Eric",
  "mr.-and-mrs.-kawooya": "Mr. & Mrs. Kawooya",
  "aunt-joan-and-family": "Aunt Joan & Family",
  "kojja-masembe": "Kojja Masembe",
  "jajja-muwulya": "Jajja Muwulya",
  "mrs.-kalinzi-spe": "Mrs. Kalinzi Spe",
  "jajja-lugasa-deo": "Jajja Lugasa Deo",
  "mr.-and-mrs.-kayita": "Mr. & Mrs. Kayita",
  "mr.-and-mrs.-tumusiime": "Mr. & Mrs. Tumusiime",
  "mr.-and-mrs.-bagenda-elijah": "Mr. & Mrs. Bagenda Elijah",
  "mr.-and-mrs.-bayrogera": "Mr. & Mrs. Bayrogera",
  "mr.-kizito-vincent": "Mr. Kizito Vincent",
  "ms.-allen-nakabuye": "Ms. Allen Nakabuye",
  "ssalongo-ne-nalongo-yiga": "Ssalongo Ne Nalongo Yiga",
  "mr.-and-mrs.-omongole": "Mr. & Mrs. Omongole",
  "ms.-deborah-namatovu": "Ms. Deborah Namatovu",
  "ms.-esther-nakamate": "Ms. Esther Nakamate",
  "aunt-nakalanzi": "Aunt Nakalanzi",
  "mr.-and-mrs.-ssemaganda": "Mr. & Mrs. Ssemaganda",
  "mr.-luyombya-steven": "Mr. Luyombya Steven",
  "aunt-rose-nakajjubi": "Aunt Rose Nakajjubi",
  "mr.-aaron-kibirige": "Mr. Aaron Kibirige",
  "mr.-james-etot": "Mr. James Etot",
  "mr.-jordan-okong": "Mr. Jordan Okong",
  "mr.-victor": "Mr. Victor",
  "ms.-lamunu-gloria-2": "Ms. Lamunu Gloria",
  "mr.-asiimwe-emmanuel": "Mr. Asiimwe Emmanuel",
  "mr.-and-mrs.-ronald-oyom": "Mr. & Mrs. Ronald Oyom",
  "mr.-jean-clement": "Mr. Jean Clement",
  "ms.-judith-masika": "Ms. Judith Masika",
  "ms.-nansamba-cissy": "Ms. Nansamba Cissy",
  "ms.-ashaba-deborah": "Ms. Ashaba Deborah",
  "ms.-kisakye-deborah": "Ms. Kisakye Deborah",
  "mr.-and-mrs.-arinaitwe-henry": "Mr. & Mrs. Arinaitwe Henry",
  "ms.-yvonne-kyoyagala": "Ms. Yvonne Kyoyagala",
  "mr.-and-mrs.-tukamuhebwa": "Mr. & Mrs. Tukamuhebwa",
  "ms.-thelma-nyakecho": "Ms. Thelma Nyakecho",
  "mr.-armstrong": "Mr. Armstrong",
  "ms.-namugerwa-ivy-olivia": "Ms. Namugerwa Ivy Olivia",
  "mr.-gerald-oyire": "Mr. Gerald Oyire",
  "ms.-nabukenya-julian": "Ms. Nabukenya Julian",
  "mr.-mugerwa-jackson": "Mr. Mugerwa Jackson",
  "mr.-marvin-luyombya": "Mr. Marvin Luyombya",
  "mr.-clever-tugume": "Mr. Clever Tugume",
  "ms.-judith-atapi": "Ms. Judith Atapi",
  "ms.-betty-mirembe": "Ms. Betty Mirembe",
  "mr.-tumwebaze-albert": "Mr. Tumwebaze Albert",
  "ms.-priscilla-achieng": "Ms. Priscilla Achieng",
  "ms.-lisa": "Ms. Lisa",
  "ms.-claire-namakula": "Ms. Claire  Namakula",
  "mr.-ssonko-ivan": "Mr. Ssonko Ivan",
  "aunt-rose-nakajjubi": "Aunt Rose Nakajjubi Kisaabwa",
  "mr.-and-mrs.-bukenya-denis": "Mr. & Mrs. Bukenya Denis",
  "mr.-and-mrs.-yiga-deo": "Mr. & Mrs. Yiga Deo",
  "kojja-ssendawula-frank": "Kojja SSendawula Frank",
  "ms.-babirye-georgia": "Ms. Babirye Georgia",
  "ms.-anitah-nalwoga": "Ms. Anitah Nalwoga",
  "mr.-lukwata-andrew-2": "Mr. Lukwata Andrew",
  "ms.-dorcus-nassove": "Ms. Dorcus Nassove",
  "mr.-kirabo-eric-2": "Mr. Kirabo Eric",
  "aunt-cathy-and-family": "Aunt Cathy & Family",
  "aunt-joan-and-family-2": "Aunt Joan & Family",
  "buyinja-family": "Buyinja Family",
  "aunt-namaganda-margret": "Aunt Namaganda Margret",
  "ms.-namala-winnie": "Ms. Namala Winnie",
  "mrs.-mugasa-becky": "Mrs. Mugasa Becky",
  "dr.-and-mrs.-enock-kisegerwa-and-family": "Dr. & Mrs. Enock Kisegerwa and family",
  "mr.-and-mrs.-rusanga": "Mr. & Mrs. Rusanga",
  "mr.-and-mrs.-ssebambulide": "Mr. & Mrs. Ssebambulide",
  "mr.-and-mrs.-mukiibi": "Mr. & Mrs. Mukiibi",
  "ms.-namayanja-sandra": "Ms. Namayanja Sandra",
  "mr.-brian-kasozi": "Mr. Brian Kasozi", 
  "eng-and-mrs-arthur-kaweesi": "Eng. & Mrs. Arthur Kaweesi",
  "engrs.-john-and-vicky-kalema": "Engrs. John & Vicky Kalema",
  "mrs.-nambasa-annet": "Mrs. Nambasa Annet",
  "mr.-samula-arthur": "Mr. Samula Arthur",
  "mr.-and-mrs.-nsumba-ruth": "Mr. & Mrs. Nsumba Ruth",
  "mr.-bwanika": "Mr. Bwanika",
  "ms.-nakajubi-agnes": "Ms. Nakajubi Agnes",
  "mr.-joshua-eruchu": "Mr. Joshua Eruchu",
  "homewise": "Homewise",
  "mr.-mabirizi-semei": "Mr. Mabirizi Semei",
  "mr.-cyril-chinedum-ozobodo": "Mr. Cyril Chinedum Ozobodo",
  "mrs.-francoise-caroline-koukam-nekui": "Mrs. Francoise Caroline Koukam Nekui",
  "mr.-azeez-adebisi": "Mr. Azeez Adebisi",
  "mr.-roland-ndombi": "Mr. Roland Ndombi",
  "ms.-josephine-ayera": "Ms. Josephine Ayera",
  "mr.-sebunya-christopher": "Mr. Sebunya Christopher",
  "ms.-charity-esenu": "Ms. Charity Esenu",
  "ms.-carol-namuddu": "Ms. Carol Namuddu",
  "mr.-muduli-david": "Mr. Muduli David",
  "ms.-nekesa-patricia": "Ms. Nekesa Patricia",
  "mr.-kugereza-martin": "Mr. Kugereza Martin",
  "mr.-kyomuhendo-twaha": "Mr. Kyomuhendo Twaha",
  "ms.-asamo-liz": "Ms. Asamo Liz",
  "mr.-emmanuel-mwaka": "Mr. Emmanuel Mwaka",
  "mr.-amanubo-amos": "Mr. Amanubo Amos",
  "mr.-emmanuel-muhumuza": "Mr. Emmanuel Muhumuza",
  "mr.-shammah-abraham-benjamin": "Mr. Shammah Abraham Benjamin",
  "mr.-natha-eric": "Mr. Natha Eric",
  "mr.-and-mrs.-lubega-martin": "Mr. & Mrs. Lubega Martin",
  "kojja-jb-mwebe": "Kojja JB Mwebe",
  "mr.-and-mrs.-asaba-ahebwa": "Mr. & Mrs. Asaba Ahebwa",
  "pr.-and-mrs.-ssemuju-jb": "Pr. & Mrs. Ssemuju JB",
  "pr.-and-mrs.-kizuula-francis": "Pr. & Mrs. Kizuula Francis",
  "pr.-and-mrs.-kakande-g.w": "Pr. & Mrs. Kakande G.W",
  "pr.-and-mrs.-nsubuga-moses": "Pr. & Mrs. Nsubuga Moses",
  "mr.-and-mrs.-ntege": "Mr. & Mrs. Ntege",
  "mrs.-bogeere": "Mrs. Bogeere",
  "mrs.-waswa mary": "Mrs. Waswa Mary",
  "mrs.-wasswa bridget": "Mrs. Wasswa Bridget",
  "mr.-and-mrs.-erima": "Mr. & Mrs. Erima",
  "mr.-and-mrs.-watima": "Mr. & Mrs. Watima",
  "mrs.-ssebadduka": "Mrs. Ssebadduka",
  "mr.-and-mrs.-kyambadde": "Mr. & Mrs. Kyambadde",
  "mr.-and-mrs.-kato simon": "Mr. & Mrs. Kato Simon",
  "mr.-and-mrs.-musinguzi": "Mr. & Mrs. Musinguzi",
  "salongo-lukwago": "Salongo Lukwago",
  "mr.-and-mrs.-kakooza": "Mr. & Mrs. Kakooza",
  "ms.-rebecca-namakula": "Ms. Rebecca Namakula",
  "mrs.-kambugu-margret": "Mrs. Kambugu Margret",
  "maama-maseruka-diana-buzigi": "Maama Maseruka/ Diana Buzigi",
  "mr.-and-mrs.-lwanga-joseph": "Mr. & Mrs. Lwanga Joseph",
  "mr.-and-mrs.-nsubuga-tom": "Mr. & Mrs. Nsubuga Tom",
  "mr.-and-mrs.-musoke-uthman": "Mr. & Mrs. Musoke Uthman",
  "mr.-and-mrs.-ssekidde-wilber": "Mr. & Mrs. Ssekidde Wilber",
  "mr.-and-mrs.-kivumbi": "Mr. & Mrs. Kivumbi",
  "mr.-and-mrs.-nteyafa": "Mr. & Mrs. Nteyafa",
  "rubaga-south-women-2": "Rubaga South Women (Two)",
  "mr.-and-mrs.-ntabazi": "Mr. & Mrs. Ntabazi",
  "maama-arthur": "Maama Arthur",
  "mr.-kawuma": "Mr. Kawuma",
  "mrs.-kazibwe-viola": "Mrs. Kazibwe Viola",
  "ms.-anita-kifeefe": "Ms. Anita Kifeefe",
  "mr.-and-mrs.-ssuubi-timothy": "Mr. & Mrs. Ssuubi Timothy",
  "divine-messengers(2)": "Divine Messengers (2)",
  "paradise-voices(2)": "Paradise Voices (2)",
  "ms.-justine-namirembe": "Ms. Justine Namirembe",
  "aunt-prossy-namugenyi": "Aunt Prossy Namugenyi",
  "remmie": "Remmie",
  "mr.-simon-kambugu": "Mr. Simon Kambugu",
  "mrs.-irene-kambonesa": "Mrs. Irene Kambonesa",
  "mrs.-hilda-mwesigwa": "Mrs. Hilda Mwesigwa",
  "mr.-kenneth-kajjora": "Mr. Kenneth Kajjora",
  "mr.-and-mrs.-bigirwamukama-henry": "Mr. & Mrs. Bigirwamukama Henry",
  "mr.-opollo-pirwot": "Mr. Opollo Pirwot",
  "mr.-bigirwamukama-henry": "Mr. Bigirwamukama Henry",
  "ms.-nabuenya-julian": "Ms. Nabuenya Julian",
  "mr.-and-mrs.-mugamba": "Mr. & Mrs. Mugamba",
  "janzi-band": "Janzi Band",
  "mr.-and-mrs.-lwanga-ian": "Mr. & Mrs. Lwanga Ian",
  "mr.-and-mrs.-nsubuga": "Mr. & Mrs. Nsubuga",
  "mr.-and-mrs.-matsiko": "Mr. & Mrs. Matsiko",
  "aunt-nanyondo": "Aunt Nanyondo",
  "mr.-and-mrs.-ssekamate": "Mr. & Mrs. Ssekamate",
};

